<?php

/**
 * Implements hook_theme().
 */
function crop_nested_theme($existing, $type, $theme, $path) {
  return [
    'image_crop_nested' => [
      'variables' => [
        'image' => NULL,
        'attributes' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_imce_supported_widgets_alter().
 */
function crop_nested_imce_supported_widgets_alter(array &$widgets) {
  $widgets[] = 'image_widget_crop_nested';
  return $widgets;
}
